spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 150
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
server:
  port: 8080

logging:
  file: ./log/blog-search.log

---
spring:
  profiles: dev
  boot:
    admin:
      url: http://127.0.0.1:8010 #server端地址
  eureka:
    client:
      serviceUrl:
        defaultZone: http://192.168.191.1:8761/eureka/
  data:
    elasticsearch:
      cluster-name: my-application #默认为elasticsearch
      cluster-nodes: 192.168.80.131:9300 #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode